### ISSUE TITLE
[BUG] 댓글을 남길 때, 한없이 길어지는 현상

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-03#247]
<img width="1432" alt="스크린샷 2019-12-06 오후 2 58 45" src="https://user-images.githubusercontent.com/20928548/70299778-29b2af00-1839-11ea-81b1-41fce1f643c4.png">

댓글이 많이 달리면 끝없이 내려갑니다.
의도된 것인지 궁금합니다!

**Comment by njh7799** [comment]
@happydhKim 일정 이상 연속으로 못달도록 수저하겠습니다 :)
