### ISSUE TITLE
[ BUG ] 컨텐츠 업로드시 내용의 이미지 비율이 맞지 않는 문제가 있습니다

### ISSUE THREAD

**Issue by load0ne** [connect-foundation/2019-03#250]
## 이슈

컨텐츠 업로드시 맞춘 Crop 과 실제 게시되고 있는 Crop이 다릅니다.

### 컨텐츠 화면

<img width="756" alt="스크린샷 2019-12-06 오후 3 04 00" src="https://user-images.githubusercontent.com/47515936/70300022-c412f280-1839-11ea-899a-31a253480a14.png">

### 업로드 시 화면

<img width="654" alt="스크린샷 2019-12-06 오후 3 03 47" src="https://user-images.githubusercontent.com/47515936/70300021-c37a5c00-1839-11ea-86c5-513a756b9f52.png">

**Comment by soyoungjeong** [comment]
어떤 경우인지 확인해보도록 하겠습니다ㅎㅎ감사합니다!
