### ISSUE TITLE
[BUG]좋아요에 react dom error

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-03#251]
좋아요 누르니 o is not a function이라는 에러가 뜨네요!! 아직 구현을 안하신 걸까요?
<img width="957" alt="스크린샷 2019-12-06 오후 3 07 58" src="https://user-images.githubusercontent.com/29801123/70300240-561afb00-183a-11ea-822d-7c03e40e2b7c.png">

**Comment by njh7799** [comment]
@aereeeee 내일까지 만들게요 광광ㅠㅠ
