### ISSUE TITLE
[BUG] 댓글이 길 경우 가로스크롤이 생성됩니다.

### ISSUE THREAD

**Issue by sphong5911** [connect-foundation/2019-03#346]
해당 사항은 text 가 들어가는 엘리먼트에 width를 주고 word-wrap 속성을 이용하시면 될 것 같습니다.
https://wit.nts-corp.com/2017/07/25/4675
해당 자료를 참고해주세요~

**Comment by njh7799** [comment]
@sphong5911 천사세요?
