### ISSUE TITLE
[버그] 로그아웃을 누르니깐 에러페이지가 나옵니다

### ISSUE THREAD

**Issue by YukJiSoo** [connect-foundation/2019-03#348]
![image](https://user-images.githubusercontent.com/30258523/70772219-385c1180-1db7-11ea-875e-0078be9f811a.png)

이쁜에러페이지 부탁드려요!

**Comment by Logqwerty** [comment]
버그 수정하였습니다. 로그아웃하면 아예 로그인 페이지로 리다이렉션하도록 만들었습니다.
