### ISSUE TITLE
[BUG] 팔로우를 했는데 팔로워에 반영되지 않습니다 

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-03#351]
![image](https://user-images.githubusercontent.com/22452742/70772354-9983e500-1db7-11ea-86e1-c75606d9d471.png)

팔로우를 했는데 팔로워 숫자가 그대로입니다 ㅠㅠ 😭

**Comment by JaeHyeonKim19** [comment]
로컬에 반영했습니다!👍 앞으로도 많은 관심 부탁드려요.
