### ISSUE TITLE
[BUG] 유아이가 좀 어색한 느낌이 들어요!

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-03#355]
<img width="723" alt="스크린샷 2019-12-13 오후 3 04 52" src="https://user-images.githubusercontent.com/40539104/70773176-0dbf8800-1dba-11ea-9cab-689ea42d6e66.png">

**Comment by njh7799** [comment]
@always-awake 반영하겠습니다! 감사합니다 :)
