### ISSUE TITLE
[BUG] 알림창 몇 초 후 사라지게하는 기능 제안

### ISSUE THREAD

**Issue by hos101010** [connect-foundation/2019-03#365]
![image](https://user-images.githubusercontent.com/26520423/70782878-62b7ca00-1dcb-11ea-8429-d4acdb892850.png)
혹시 이거 엑스 안누르고 몇초후에 사라지게 하는건 어떨까요?
단순한 제안입니당!

**Comment by soyoungjeong** [comment]
좋은 제안 감사합니다! 업데이트하겠습니다😊
